# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69178a30710b366425a1069feef1035730241f33f844c1a3fa8b8f178570ec67cd31f2d73b1a982308e42c43518f9849faafc1925a9b5cc404a8742522100177

test:
  secret_key_base: b88e511f4f1966b1e0fc1e4dd4394e7e2999c9c2c1366573a0f8217cca9806b8dffe996b87e2e18db36d557657253835f87af62d196db3717460835e88a7c96c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
